#!/bin/bash

TMPDIR="/tmp/xenserver-check_mk-$$" 
AGENTPACK="check_mk-1.2.6p10.tar.gz" 

mkdir $TMPDIR && cd $TMPDIR

yum --enablerepo=base -y install xinetd
wget http://mathias-kettner.de/download/$AGENTPACK -O $AGENTPACK

rpm -qa | grep -i xinetd

tar -xzf  $AGENTPACK
rm $AGENTPACK

SUBDIR=$(ls)

tar xzf  $SUBDIR/agents.tar.gz

rpm -Uvh check-mk-agent*.noarch.rpm




